export const ADDRESSES = [
  {
    id: 1,
    userId: 1,
    street: 'Av. Aconquija',
    number: '50',
    city: 'Yerba Buena',
    state: 'Tucuman',
    country: 'Argentina',
  },
  {
    id: 2,
    userId: 3,
    street: 'Av. Santa Fe',
    number: '1200',
    city: 'Buenos Aires',
    state: 'Buenos Aires',
    country: 'Argentina',
  },
  {
    id: 3,
    userId: 3,
    street: 'Calle Corrientes',
    number: '456',
    city: 'Rosario',
    state: 'Santa Fe',
    country: 'Argentina',
  },
  {
    id: 4,
    userId: 2,
    street: 'Av. San Martín',
    number: '742',
    city: 'Mendoza',
    state: 'Mendoza',
    country: 'Argentina',
  },
  {
    id: 5,
    userId: 1,
    street: 'Av. Colón',
    number: '221',
    city: 'Córdoba',
    state: 'Córdoba',
    country: 'Argentina',
  },
  {
    id: 6,
    userId: 4,
    street: 'Calle Mitre',
    number: '320',
    city: 'San Miguel de Tucumán',
    state: 'Tucumán',
    country: 'Argentina',
  },
  {
    id: 7,
    userId: 1,
    street: 'Calle Sarmiento',
    number: '123',
    city: 'Rosario',
    state: 'Santa Fe',
    country: 'Argentina',
  },
  {
    id: 8,
    userId: 2,
    street: 'Av. 9 de Julio',
    number: '100',
    city: 'Buenos Aires',
    state: 'Buenos Aires',
    country: 'Argentina',
  },
  {
    id: 9,
    userId: 5,
    street: 'Calle Lamadrid',
    number: '1900',
    city: 'Yerba Buena',
    state: 'Tucumán',
    country: 'Argentina',
  },
  {
    id: 10,
    userId: 1,
    street: 'Av Sarmiento',
    number: '2300',
    city: 'San Miguel de Tucumán',
    state: 'Tucuman',
    country: 'Argentina',
  },
  {
    id: 11,
    userId: 5,
    street: 'Blanco Encalada',
    number: '200',
    city: 'Buenos Aires',
    state: 'Buenos Aires',
    country: 'Argentina',
  },
  {
    id: 12,
    userId: 3,
    street: '25 de Mayo',
    number: '3300',
    city: 'La Plata',
    state: 'Buenos Aires',
    country: 'Argentina',
  },
]
