export const STUDIES = [
  {
    id: 1,
    userId: 1,
    university: 'UNT',
    career: 'Abogacia',
    graduated: true,
  },
  {
    id: 2,
    userId: 2,
    university: 'UBA',
    career: 'Relaciones exteriores',
    graduated: false,
  },
  {
    id: 3,
    userId: 3,
    university: 'UNR',
    career: 'Ingeniería Informática',
    graduated: true,
  },
  {
    id: 4,
    userId: 4,
    university: 'UNCuyo',
    career: 'Psicología',
    graduated: false,
  },
  {
    id: 5,
    userId: 5,
    university: 'UNC',
    career: 'Diseño Gráfico',
    graduated: true,
  },
  {
    id: 6,
    userId: 1,
    university: 'UNT',
    career: 'Contador Público',
    graduated: false,
  },
  {
    id: 7,
    userId: 2,
    university: 'UNR',
    career: 'Administración de empresas',
    graduated: true,
  },
  {
    id: 8,
    userId: 3,
    university: 'UBA',
    career: 'Ingeniería mecánica',
    graduated: true,
  },
  {
    id: 9,
    userId: 4,
    university: 'UNLP',
    career: 'Arquitectura',
    graduated: false,
  },
]
