export const USERS = [
  {
    id: 1,
    email: 'dantesarmiento@admin.com',
    password: 'dante123',
    role: 'admin',
    firstName: 'Dante',
    lastName: 'Sarmiento',
  },
  {
    id: 2,
    email: 'mariagonzalez@client.com',
    password: 'maria123',
    role: 'client',
    firstName: 'Maria',
    lastName: 'Gonzalez',
  },
  {
    id: 3,
    email: 'emilianomartinez@admin.com',
    password: 'emiliano123',
    role: 'admin',
    firstName: 'Emiliano',
    lastName: 'Martinez',
  },
  {
    id: 4,
    email: 'pedroperez@user.com',
    password: 'pedro123',
    role: 'client',
    firstName: 'Pedro',
    lastName: 'Perez',
  },
  {
    id: 5,
    email: 'sofiasanchez@user.com',
    password: 'sofia123',
    role: 'client',
    firstName: 'Sofia',
    lastName: 'Sanchez',
  },
  {
    id: 6,
    email: 'carlosruiz20@admin.com',
    password: 'carlos123',
    role: 'admin',
    firstName: 'Carlos',
    lastName: 'Ruiz',
  }
]