export const USERS = [
  {
    id: 1,
    email: 'dantesarmiento@admin.com',
    password: 'dante123',
    role: 'admin',
    firstName: 'Dante',
    lastName: "Sarmiento",
    data: {
      address: 'Calle Falsa 123',
      studies: 'Ingeniería Informática',
    },
  },
  {
    id: 2,
    email: 'mariagonzalez@admin.com',
    password: 'maria123',
    role: 'admin',
    firstName: 'Maria',
    lastName: "Gonzalez",
    data: {
      address: 'Av. Libertador 221',
      studies: 'Diseño Gráfico',
    },
  },
  {
    id: 3,
    email: 'emilianomartinez@admin.com',
    password: 'emiliano123',
    role: 'admin',
    firstName: 'Emiliano',
    lastName: "Martinez",
    data: {
      address: 'Calle Falsa 123',
      studies: 'Ingeniería Informática',
    },
  },
  {
    id: 4,
    email: 'pedroperez@user.com',
    password: 'pedro123',
    role: 'client',
    firstName: 'Pedro',
    lastName: "Perez",
    data: {
      address: 'Av. Siempre Viva 742',
      studies: 'Psicología',
    },
  },
  {
    id: 5,
    email: 'sofiasanchez@user.com',
    password: 'sofia123',
    role: 'client',
    firstName: 'Sofia',
    lastName: "Sanchez",
    data: {
      address: 'Av. Libertador 221',
      studies: 'Diseño Gráfico',
    },
  },
  {
    id: 6,
    email: 'carlosramirez@user.com',
    password: 'carlos123',
    role: 'client',
    firstName: 'Carlos',
    lastName: "Ramirez",
    data: {
      address: 'Av. Libertador 221',
      studies: 'Diseño Gráfico',
    },
  },
  {
    id: 7,
    email: 'lionelmessi@admin.com',
    password: 'lionel123',
    role: 'admin',
    firstName: 'Lionel',
    lastName: "Messi",
    data: {
      address: 'Calle Falsa 123',
      studies: 'Ingeniería Informática',
    },
  },
  {
    id: 8,
    email: 'belenruiz@user.com',
    password: 'belen123',
    role: 'client',
    firstName: 'Belen',
    lastName: "Ruiz",
    data: {
      address: 'Av. Libertador 221',
      studies: 'Diseño Gráfico',
    },
  },
  {
    id: 9,
    email: 'florenciamartinez@user.com',
    password: 'florencia123',
    role: 'client',
    firstName: 'Sofia',
    lastName: "Sanchez",
    data: {
      address: 'Av. Libertador 221',
      studies: 'Diseño Gráfico',
    },
  },
]